name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.7'  # You can change to the version you're using

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (ensure you have test cases configured in your Django project)
      - name: Run tests
        run: |
          python manage.py test  # Running Django tests

      # Optional: Run linters (like flake8 or pylint)
      - name: Run linter (flake8 example)
        run: |
          pip install flake8
          flake8 .  # Check your Python files for linting issues

      # Optional: Check for code formatting (black example)
      - name: Check code formatting (black example)
        run: |
          pip install black
          black --check .  # Will fail if code isn't formatted properly
